# Generated by Django 4.2.16 on 2024-11-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(null=True, unique=True, upload_to='profile_pics/'),
        ),
    ]
