# Generated by Django 4.2.16 on 2024-11-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_rename_user_product_supplier'),
        ('user', '0006_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='product_requests',
            field=models.ManyToManyField(to='product.product'),
        ),
    ]
