# Generated by Django 4.2.16 on 2024-11-06 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_product_requests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='product_requests',
        ),
    ]
