# Generated by Django 4.2.16 on 2024-11-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_user_product_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='koiBi',
            field=models.CharField(default='Zaheer Ahmad', max_length=10),
        ),
    ]
