# Generated by Django 4.2.16 on 2024-11-07 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_user_koibi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='koiBi',
        ),
    ]
