# Generated by Django 4.2.16 on 2024-11-05 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_claim'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='claim',
            unique_together={('product',)},
        ),
    ]
