# Generated by Django 4.2.16 on 2024-11-06 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0005_product_status_claimrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claimrequest',
            name='product',
        ),
        migrations.RemoveField(
            model_name='claimrequest',
            name='requester',
        ),
        migrations.AddField(
            model_name='product',
            name='requesting_users',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requested_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Claim',
        ),
        migrations.DeleteModel(
            name='ClaimRequest',
        ),
    ]
