# Generated by Django 4.2.16 on 2024-11-06 11:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0007_remove_product_requesting_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_claimed',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='requesting_users',
            field=models.ManyToManyField(blank=True, related_name='requested_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
