# Generated by Django 4.2.16 on 2024-11-06 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_product_requesting_users_request_claimed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claimed',
            old_name='claimed_by',
            new_name='pro_dene_wala',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='request_by',
            new_name='zarorat_mand',
        ),
    ]
