# Generated by Django 4.2.16 on 2024-11-06 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_rename_claimed_by_claimed_pro_dene_wala_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='user',
            new_name='supplier',
        ),
    ]
