# Generated by Django 4.2.16 on 2024-11-07 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_request_request_status_delete_claimed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('rejected', 'rejected'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
    ]
